#yamllint disable
name: GSI With product Partition..

on:
#  release:
#    types: [published]
#  push:
#    branches:
#      - master
#    paths:
#      - '.config'
#  schedule:
#    - cron: 0 8 * * 5
  watch:
    types: [started]
    
env:
  ROM_URL: https://oxygenos.oneplus.net/OnePlus8ProOxygen_15.O.22_OTA_022_all_2008080055_6e4f8eb44c10429a.zip
  ROM_NAME: OxygenOS
  ZIP_NAME: Oneplus8PRO
  DOWNLOADEDROM: readlink -f romishere/* 
  TZ: Asia/Kolkata
  MIR: wet
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - name: Checkout
         uses: actions/checkout@master
       
       - name: Clean Up
         run: |
           docker rmi `docker images -q`
           sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d
           sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php*
           sudo -E apt-get update
           sudo -E apt-get install wget
           sudo -E apt-get -y autoremove --purge
           sudo -E apt-get clean 
           
       - name: Initializing environment
         run: |
            sudo -E apt-get -qq update
            sudo -E apt-get -qq install git openjdk-8-jdk wget

       
       - name: Clone ErfanGSI Source Code
         run: git clone --recurse-submodules https://github.com/erfanoabdi/ErfanGSIs.git
       
       - name: Setting up ErfanGSI requirements
         run: |
              sudo chmod -R 777 ErfanGSIs
              cd ErfanGSIs
              sudo bash setup.sh
       
       - name: Download Stock Rom & Generate GSI
         run: |
              sudo mkdir romishere
              cd romishere
              sudo wget $ROM_URL
              cd ..
              wget https://raw.githubusercontent.com/dikeckaan/Sienna-GSI-Automation/master/merge.sh
              chmod +x merge.sh
              chmod +x make.sh
              sudo ./merge.sh $ROM_NAME $DOWNLOADEDROM
              chmod +x make.sh       
       - name: Zip AB and upload 
         run: |
              sudo ./make.sh cache/system-new $ROM_NAME AB output/
              sudo chmod -R 777 ErfanGSIs/output
              zip -r ErfanGSIs/output/$ZIP_NAME-GSI-AB.7z ErfanGSIs/output/*-AB-*.img
              curl -sL https://git.io/file-transfer | sh
              ./transfer $MIR ErfanGSIs/output/$ZIP_NAME-GSI-AB.7z          
       
       - name: Print build info
         run: |
              cat ErfanGSIs/output/*-AB-*.txt
         
            
#yamllint enable
