#yamllint disable

name: GSI..

on:
#  release:
#    types: [published]
#  push:
#    branches:
#      - master
#    paths:
#      - '.config'
#  schedule:
#    - cron: 0 8 * * 5
  watch:
    types: [started]
    
env:
  ROM_URL: https://downloads.sourceforge.net/project/testbuildss/daisy/ion-2.9.a-EOL-daisy-20200823-1246-UNOFFICIAL-Preview.zip?r=android-app%3A%2F%2Forg.telegram.messenger%2F&ts=1598716243&use_mirror=master
  ROM_NAME: Generic
  ZIP_NAME: IONOS
  TZ: Asia/Kolkata
  MIR: wet
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - name: Checkout
         uses: actions/checkout@master
       
       - name: Clean Up
         run: |
           docker rmi `docker images -q`
           sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d
           sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php*
           sudo -E apt-get update
           sudo -E apt-get -y autoremove --purge
           sudo -E apt-get clean 
           
       - name: Initializing environment
         run: |
            sudo -E apt-get -qq update
            sudo -E apt-get -qq install git openjdk-8-jdk wget

       
       - name: Clone ErfanGSI Source Code
         run: |
              cd ~/
              git clone --recurse-submodules https://github.com/erfanoabdi/ErfanGSIs.git
       
       - name: Setting up ErfanGSI requirements
         run: |
              sudo chmod -R 777 ErfanGSIs
              cd ErfanGSIs
              sudo bash setup.sh
       
       - name: Download Stock Rom & Generate GSI
         run: sudo bash ~/ErfanGSIs/url2GSI.sh $ROM_URL $ROM_NAME
       
       - name: upload tool downloading
         run: |
               mkdir final
               sudo chmod -R 777 ErfanGSIs/output
               curl -sL https://git.io/file-transfer | sh
       - name: Zip AB and upload 
         run: |
              zip -r ErfanGSIs/output/$ZIP_NAME-GSI-AB.7z ErfanGSIs/output/*-AB-*.img
              ./transfer $MIR ErfanGSIs/output/$ZIP_NAME-GSI-AB.7z
              
       
       - name: upload Aonly
         run: |
              zip -r ErfanGSIs/output/$ZIP_NAME-GSI-AB.7z ErfanGSIs/output/*-Aonly-*.img
              ./transfer $MIR ErfanGSIs/output/$ZIP_NAME-GSI-Aonly.7z
                    
       - name: Print build info
         run: |
              cat ErfanGSIs/output/*-AB-*.txt
         
            
#yamllint enable
